services:
  - type: web
    name: wonderfxai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: 7345167907:AAFn5YM5pTZn444fZPaEIbQboud5sGfvPCc
